[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.daws88s.space

[redis]
localhost

[user]
user-dev.daws88s.space

[cart]
cart-dev.daws88s.space

[mysql]
mysql-dev.daws88s.space

[shipping]
shipping-dev.daws88s.space

[rabbitmq]
rabbitmq-dev.daws88s.space

[payment]
payment-dev.daws88s.space

[frontend]
frontend-dev.daws88s.space